---
title: "SocCult Analysis of ABM"
author: "Nina Illum and Verus Juhasz"
date: "24/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
pacman::p_load(tidyverse, plyr)

```


## Load data

```{r load ESS data}
# load raw data
raw_data02 <- as.tibble(read_csv("exam_data/ESS1e06.6/ESS1e06.6_F1.csv"))
raw_data10 <- as.tibble(read_csv("exam_data/ESS5e03.4/ESS5e03.4_F1.csv"))
raw_data18 <- as.tibble(read_csv("exam_data/ESS9e03.1/ESS9e03.1_F1.csv"))

# select relevant data (2002)
data02 <- raw_data02 %>% 
  select(
    essround,
    edition,
    idno,
    # Respondent's identification number
    inwyr,
    # Year of interview
    cntry,
    # Country
    lrscale,
    # Placement on left right scale
    
# Cooperation variable
    ipudrst,
    # Important to understand different people

# Weights
    dweight,
    # Designer weights
    pspwght,
    # Post-Stratification weights
    pweight
    # Population weights
  ) %>% 
  mutate(
    cntry = as_factor(cntry),
    year = inwyr
    )

# select relevant data (2010)
data10 <- raw_data10 %>% 
  select(
    essround,
    edition,
    idno,
    # Respondent's identification number
    inwyys,
    # Year of interview
    cntry,
    # Country
    lrscale,
    # Placement on left right scale
    
# Cooperation variable
    ipudrst,
    # Important to understand different people
    
# Weights
    dweight,
    # Designer weights
    pspwght,
    # Post-Stratification weights
    pweight
    # Population weights
  ) %>% 
  mutate(
    cntry = as_factor(cntry),
    year = inwyys
    )

# select relevant data (2018)
data18 <- raw_data18 %>%
  select(
    essround,
    edition,
    idno,
    # Respondent's identification number
    inwyys,
    # Year of interview
    cntry,
    # Country
    lrscale,
    # Placement on left right scale
    
# Cooperation variable
    ipudrst,
    # Important to understand different people
    
# Weights
    dweight,
    # Designer weights
    pspwght,
    # Post-Stratification weights
    pweight
    # Population weights
  ) %>% 
  mutate(
    cntry = as_factor(cntry),
    year = inwyys
    )

```


```{r preprocessing function}

preprocess.function <- function(dat) {
  dat %>% 
  filter(
      ticks < 2921) %>% 
  mutate(
    trial = str_extract(file_id, "\\d{1,2}")
  )
}

```


```{r load model output}

files_DK <- list.files("netlogo_output/ABM_code final running/", pattern = "^output-data_DK.*?\\.csv", full.names = TRUE, recursive = T)

df_DK <- purrr::map_df(files_DK, function(x) {
	data <- read.csv(x, header=TRUE)
	cbind(file_id = x, data)
	})

df_DK <- df_DK %>% 
  preprocess.function() %>% 
  mutate(
    trial = as.factor(trial),
    ticks = as.factor(ticks),
    cntry = "DK"
  )

```


```{r}

df_DK %>% 
  group_by(trial) %>% 
  #filter(trial == 10
  #       ) %>% 
  ggplot() +
  aes(x = opinion,
      color = ticks,
      fill = ticks,
      alpha = 0.2) +
  geom_density()

count(df_DK$opinion == 1)


```



## Model Validation

```{r data formatting}

country_list <- c("DK",
                 "FR",
                 "GB")
## 2010
# Denmark
data_10_valid_DK <- data10 %>% 
  select(
    idno,
    inwyys,
    cntry,
    lrscale
  ) %>% 
  filter(
    cntry == "DK",
    lrscale < 11
  ) %>% 
  mutate(
    opinion =  (lrscale * (2/11)) - 1
  )

# France
data_10_valid_FR <- data10 %>% 
  select(
    idno,
    inwyys,
    cntry,
    lrscale
  ) %>% 
  filter(
    cntry == "FR",
    lrscale < 11
  ) %>% 
  mutate(
    opinion =  (lrscale * (2/11)) - 1
  )

# Great Britain
data_10_valid_GB <- data10 %>% 
  select(
    idno,
    inwyys,
    cntry,
    lrscale
  ) %>% 
  filter(
    cntry == "GB",
    lrscale < 11
  ) %>% 
  mutate(
    opinion =  (lrscale * (2/11)) - 1
  )


## 2018
# Denmark
data_18_valid_DK <- data18 %>% 
  select(
    idno,
    inwyys,
    cntry,
    lrscale
  ) %>% 
  filter(
    cntry == "DK",
    lrscale < 11
  ) %>% 
  mutate(
    opinion =  (lrscale * (2/11)) - 1
  )

# France
data_18_valid_FR <- data18 %>% 
  select(
    idno,
    inwyys,
    cntry,
    lrscale
  ) %>% 
  filter(
    cntry == "FR",
    lrscale < 11
  ) %>% 
  mutate(
    opinion =  (lrscale * (2/11)) - 1
  )

# Great Britain
data_18_valid_GB <- data18 %>% 
  select(
    idno,
    inwyys,
    cntry,
    lrscale
  ) %>% 
  filter(
    cntry == "GB",
    lrscale < 11
  ) %>% 
  mutate(
    opinion =  (lrscale * (2/11)) - 1
  )

```


### Model Validation with the polarization index
The 

```{r new data formatting}

# function for calculating variance of distances in opinions of random sample (N = 64)
func <- function(d) {
  sam = sample(nrow(d), 64)
  l <- vector(length = 0)
  for (v in sam) { 
    l <- c(l, abs(d$opinion[v]-d$opinion))
  }
return(var(l))}

# calculate polarization index
pol_index_10_DK <- func(data_10_valid_DK)
pol_index_10_FR <- func(data_10_valid_FR)
pol_index_10_GB <- func(data_10_valid_GB)
pol_index_18_DK <- func(data_18_valid_DK)
pol_index_18_FR <- func(data_18_valid_FR)
pol_index_18_GB <- func(data_18_valid_GB)

year <- c(2010, 2010, 2010, 2018, 2018, 2018)
country <- c("DK", "FR", "GB", "DK", "FR", "GB")
pol_index <- c(pol_index_10_DK, pol_index_10_FR, pol_index_10_GB, pol_index_18_DK, pol_index_18_FR, pol_index_18_GB)

pol_df <- data.frame(year, country, pol_index)

write.csv(pol_df,".\\Calculated_polarization_index.csv", row.names = FALSE)

```


### T-test

```{r t-test}

```







