---
title: "SC Data test"
author: "Nina Illum"
date: "10/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
pacman::p_load(tidyverse)

# for working directory troubles
#setwd("C:/Users/ninai/Docs/Uni/4. semester/Social and Cultural Dynamics in Cognition/Exam/SocCult_ExamProj")

```


```{r load data, 2002}

# load data
raw_data <- read_csv("exam_data/ESS1e06.6/ESS1e06.6_F1.csv")

# select relevant data
data <- raw_data %>% 
  select(
    idno,
    # Respondent's identification number
    inwdd,
    # Day of month of interview
    inwmm,
    # Month of interview
    inwyr,
    # Year of interview
    cntry,
    # Country
    lrscale,
    # Placement on left right scale
    
# Inequality relevant variables
    empl,
    # Employment status
    #smbtjob,
    # Get a similar or better job with another employer -> not in other dataset
    domicil,
    # Domicile, respondent's description
    edulvla,
    # Highest level of education
    eisced,
    # Highest level of education, ES - ISCED ------> not familiar with the scale !!
    mainact,
    # Main activity last 7 days (work, education, unemployed, etc.)
    mnactic,
    # Main activity, last 7 days. All respondents. Post coded ------> seems to include all countries compared to mainact
    hincfel,
    # Feeling about household's income nowadays'
    
# Cooperation relevant variables
    ppltrst,
    # Most people can be trusted or you can't be too careful
    pplfair,
    # Most people try to take advantage of you, or try to be fair
    pplhlp,
    # Most of the time people helpful or mostly looking out for themselves
    #discpol,
    # Discuss politics/current affairs, how often -> not in other dataset
    #impsppl,
    # To be a good citizen: how important to support people worse off -> not in other dataset
    impopin,
    # To be a good citizen: how important to form independent opinion
    ipudrst,
    # Important to understand different people
    impfree,
    # Important to make own decisions and be free
    
# Left-right opinion relevant variables
    ginveco,
    # The less government intervenes in economy, the better for country
    gincdif,
    # Government should reduce differences in income levels
    needtru,
    # Employees need strong trade unions to protect work conditions/wages
    imprich,
    # Important to be rich, have money and expensive things
    ipeqopt,
    # Important that people are treated equally and have equal opportunities
    iphlppl,
    # Important to help people and care for others well-being
    ipstrgv,
    # Important that government is strong and ensures safety
    
# Religion relevant variables
    rlgblg,
    # Belonging to particular religion or denomination
    rlgdnm,
    # Religion or denomination belonging to at present
    rlgblge,
    # Ever belonging to particular religion or denomination
    rlgdnme,
    # Religion or denomination belonging to in the past
    rlgdgr,
    # How religious are you
    
# Weights
    dweight,
    # Designer weights
    pspwght,
    # Post-Stratification weights
    pweight
    # Population weights
  ) %>% 
  mutate(
    cntry = as_factor(cntry),
    date = inwdd,
    month = inwmm,
    year = inwyr,
    edulvl = edulvla
    )


```


```{r load data, 2018}

# load data
raw_data18 <- read_csv("exam_data/ESS9e03.1/ESS9e03.1_F1.csv")

# select relevant data
data18 <- raw_data18 %>%
  select(
    idno,
    # Respondent's identification number
    inwdds,
    # Day of month of interview
    inwmms,
    # Month of interview
    inwyys,
    # Year of interview
    cntry,
    # Country
    lrscale,
    # Placement on left right scale
    
# Inequality relevant variables
    emplrel, # changed
    # Employment relation,
    domicil,
    # Domicile, respondent's description
    edulvlb,
    # Highest level of education
    eisced,
    # Highest level of education, ES - ISCED ------> not familiar with the scale !!
    mainact,
    # Main activity last 7 days (work, education, unemployed, etc.)
    mnactic,
    # Main activity, last 7 days. All respondents. Post coded ------> seems to include all countries compared to mainact
    hincfel,
    # Feeling about household's income nowadays'
    
# Cooperation relevant variables
    ppltrst,
    # Most people can be trusted or you can't be too careful
    pplfair,
    # Most people try to take advantage of you, or try to be fair
    pplhlp,
    # Most of the time people helpful or mostly looking out for themselves
    #impopin,
    # To be a good citizen: how important to form independent opinion
    ipudrst,
    # Important to understand different people
    impfree,
    # Important to make own decisions and be free
    
# Left-right opinion relevant variables
    #ginveco,
    # The less government intervenes in economy, the better for country
    gincdif,
    # Government should reduce differences in income levels
    #needtru,
    # Employees need strong trade unions to protect work conditions/wages
    imprich,
    # Important to be rich, have money and expensive things
    ipeqopt,
    # Important that people are treated equally and have equal opportunities
    iphlppl,
    # Important to help people and care for others well-being
    ipstrgv,
    # Important that government is strong and ensures safety
    
# Religion relevant variables
    rlgblg,
    # Belonging to particular religion or denomination
    rlgdnm,
    # Religion or denomination belonging to at present
    rlgblge,
    # Ever belonging to particular religion or denomination
    rlgdnme,
    # Religion or denomination belonging to in the past
    rlgdgr,
    # How religious are you
    
# Weights
    dweight,
    # Designer weights
    pspwght,
    # Post-Stratification weights
    pweight
    # Population weights
  ) %>% 
  mutate(
    cntry = as_factor(cntry),
    date = inwdds,
    month = inwmms,
    year = inwyys,
    edulvl = edulvlb
    )

```


```{r plot the data}

data %>%
  #subset(cntry == "SI" | cntry == "DK") %>% 
  ggplot() +
  aes(x = lrscale, color = cntry, fill = cntry) +
  geom_bar() +
  coord_cartesian(xlim = c(0, 10)) + 
  facet_wrap(vars(cntry))

data18 %>%
  #subset(cntry == "SI" | cntry == "DK") %>% 
  ggplot() +
  aes(x = lrscale, color = cntry, fill = cntry) +
  geom_bar() +
  coord_cartesian(xlim = c(0, 10)) + 
  facet_wrap(vars(cntry))

```

