---
title: "ESS Political data (2002-2010-2018)"
author: "Nina Illum"
date: "10/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
pacman::p_load(tidyverse, plyr)

# for working directory troubles
#setwd("C:/Users/ninai/Docs/Uni/4. semester/Social and Cultural Dynamics in Cognition/Exam/SocCult_ExamProj")

```


```{r load data, 2002}

# load data
raw_data02 <- as.tibble(read_csv("exam_data/ESS1e06.6/ESS1e06.6_F1.csv"))

# select relevant data
data02 <- raw_data02 %>% 
  select(
    essround,
    edition,
    idno,
    # Respondent's identification number
    inwdd,
    # Day of month of interview
    inwmm,
    # Month of interview
    inwyr,
    # Year of interview
    cntry,
    # Country
    lrscale,
    # Placement on left right scale
    
# Inequality relevant variables
    empl,
    # Employment status
    #smbtjob,
    # Get a similar or better job with another employer -> not in other dataset
    domicil,
    # Domicile, respondent's description
    edulvla,
    # Highest level of education
    eisced,
    # Highest level of education, ES - ISCED ------> the ESS scale
    mainact,
    # Main activity last 7 days (work, education, unemployed, etc.)
    mnactic,
    # Main activity, last 7 days. All respondents. Post coded ------> seems to include all countries compared to mainact
    hincfel,
    # Feeling about household's income nowadays'
    
# Cooperation relevant variables
    ppltrst,
    # Most people can be trusted or you can't be too careful
    pplfair,
    # Most people try to take advantage of you, or try to be fair
    pplhlp,
    # Most of the time people helpful or mostly looking out for themselves
    #discpol,
    # Discuss politics/current affairs, how often -> not in other dataset
    #impsppl,
    # To be a good citizen: how important to support people worse off -> not in other dataset
    impopin,
    # To be a good citizen: how important to form independent opinion
    ipudrst,
    # Important to understand different people
    impfree,
    # Important to make own decisions and be free
    
# Left-right opinion relevant variables
    ginveco,
    # The less government intervenes in economy, the better for country
    gincdif,
    # Government should reduce differences in income levels
    needtru,
    # Employees need strong trade unions to protect work conditions/wages
    imprich,
    # Important to be rich, have money and expensive things
    ipeqopt,
    # Important that people are treated equally and have equal opportunities
    iphlppl,
    # Important to help people and care for others well-being
    ipstrgv,
    # Important that government is strong and ensures safety
    
# Religion relevant variables
    rlgblg,
    # Belonging to particular religion or denomination
    rlgdnm,
    # Religion or denomination belonging to at present
    rlgblge,
    # Ever belonging to particular religion or denomination
    rlgdnme,
    # Religion or denomination belonging to in the past
    rlgdgr,
    # How religious are you
    
# Weights
    dweight,
    # Designer weights
    pspwght,
    # Post-Stratification weights
    pweight
    # Population weights
  ) %>% 
  mutate(
    cntry = as_factor(cntry),
    date = inwdd,
    month = inwmm,
    year = inwyr,
    edulvl = edulvla
    )


```

```{r load data, 2010}

# load data
raw_data10 <- as.tibble(read_csv("exam_data/ESS5e03.4/ESS5e03.4_F1.csv"))

# select relevant data
data10 <- raw_data10 %>% 
  select(
    essround,
    edition,
    idno,
    # Respondent's identification number
    inwdds,
    # Day of month of interview
    inwmms,
    # Month of interview
    inwyys,
    # Year of interview
    cntry,
    # Country
    lrscale,
    # Placement on left right scale
    
# Inequality relevant variables
    #empl,
    # Employment status
    #smbtjob,
    # Get a similar or better job with another employer -> not in other dataset
    domicil,
    # Domicile, respondent's description
    edulvlb,
    # Highest level of education
    eisced,
    # Highest level of education, ES - ISCED ------> the ESS scale
    mainact,
    # Main activity last 7 days (work, education, unemployed, etc.)
    mnactic,
    # Main activity, last 7 days. All respondents. Post coded ------> seems to include all countries compared to mainact
    hincfel,
    # Feeling about household's income nowadays'
    
# Cooperation relevant variables
    ppltrst,
    # Most people can be trusted or you can't be too careful
    pplfair,
    # Most people try to take advantage of you, or try to be fair
    pplhlp,
    # Most of the time people helpful or mostly looking out for themselves
    #discpol,
    # Discuss politics/current affairs, how often -> not in other dataset
    #impsppl,
    # To be a good citizen: how important to support people worse off -> not in other dataset
    #impopin,
    # To be a good citizen: how important to form independent opinion
    ipudrst,
    # Important to understand different people
    impfree,
    # Important to make own decisions and be free
    
# Left-right opinion relevant variables
    #ginveco,
    # The less government intervenes in economy, the better for country
    gincdif,
    # Government should reduce differences in income levels
    #needtru,
    # Employees need strong trade unions to protect work conditions/wages
    imprich,
    # Important to be rich, have money and expensive things
    ipeqopt,
    # Important that people are treated equally and have equal opportunities
    iphlppl,
    # Important to help people and care for others well-being
    ipstrgv,
    # Important that government is strong and ensures safety
    
# Religion relevant variables
    rlgblg,
    # Belonging to particular religion or denomination
    rlgdnm,
    # Religion or denomination belonging to at present
    rlgblge,
    # Ever belonging to particular religion or denomination
    rlgdnme,
    # Religion or denomination belonging to in the past
    rlgdgr,
    # How religious are you
    
# Weights
    dweight,
    # Designer weights
    pspwght,
    # Post-Stratification weights
    pweight
    # Population weights
  ) %>% 
  mutate(
    cntry = as_factor(cntry),
    date = inwdds,
    month = inwmms,
    year = inwyys,
    edulvl = edulvlb
    )

```


```{r load data, 2018}

# load data
raw_data18 <- as.tibble(read_csv("exam_data/ESS9e03.1/ESS9e03.1_F1.csv"))

# select relevant data
data18 <- raw_data18 %>%
  select(
    essround,
    edition,
    idno,
    # Respondent's identification number
    inwdds,
    # Day of month of interview
    inwmms,
    # Month of interview
    inwyys,
    # Year of interview
    cntry,
    # Country
    lrscale,
    # Placement on left right scale
    
# Inequality relevant variables
    emplrel, # changed
    # Employment relation,
    domicil,
    # Domicile, respondent's description
    edulvlb,
    # Highest level of education
    eisced,
    # Highest level of education, ES - ISCED ------> the ESS scale
    mainact,
    # Main activity last 7 days (work, education, unemployed, etc.)
    mnactic,
    # Main activity, last 7 days. All respondents. Post coded ------> seems to include all countries compared to mainact
    hincfel,
    # Feeling about household's income nowadays'
    
# Cooperation relevant variables
    ppltrst,
    # Most people can be trusted or you can't be too careful
    pplfair,
    # Most people try to take advantage of you, or try to be fair
    pplhlp,
    # Most of the time people helpful or mostly looking out for themselves
    #impopin,
    # To be a good citizen: how important to form independent opinion
    ipudrst,
    # Important to understand different people
    impfree,
    # Important to make own decisions and be free
    
# Left-right opinion relevant variables
    #ginveco,
    # The less government intervenes in economy, the better for country
    gincdif,
    # Government should reduce differences in income levels
    #needtru,
    # Employees need strong trade unions to protect work conditions/wages
    imprich,
    # Important to be rich, have money and expensive things
    ipeqopt,
    # Important that people are treated equally and have equal opportunities
    iphlppl,
    # Important to help people and care for others well-being
    ipstrgv,
    # Important that government is strong and ensures safety
    
# Religion relevant variables
    rlgblg,
    # Belonging to particular religion or denomination
    rlgdnm,
    # Religion or denomination belonging to at present
    rlgblge,
    # Ever belonging to particular religion or denomination
    rlgdnme,
    # Religion or denomination belonging to in the past
    rlgdgr,
    # How religious are you
    
# Weights
    dweight,
    # Designer weights
    pspwght,
    # Post-Stratification weights
    pweight
    # Population weights
  ) %>% 
  mutate(
    cntry = as_factor(cntry),
    date = inwdds,
    month = inwmms,
    year = inwyys,
    edulvl = edulvlb
    )

```

```{r load gini-data: Data from OECD}

# meta data
#gini_meta_data <- as.tibble(read_csv("exam_data/API_SI.POV.GINI_DS2_en_csv_v2_2357065/Metadata_Indicator_API_SI.POV.GINI_DS2_en_csv_v2_2357065.csv"))

# load data
gini_data1 <- as.tibble(read_csv("exam_data/DP_LIVE_14052021101600112.csv")) %>% 
  select(LOCATION,
         TIME,
         Value) %>% 
  filter(grepl('BEL|CHE|CZE|DEU|DNK|ESP|FIN|FRA|GBR|HUN|IRL|NLD|NOR|POL|PRT|SWE|SVN',
               LOCATION)) %>% 
  mutate(cntry = recode(LOCATION,
                        'BEL' = 'BE',
                        'CHE' = 'CH',
                        'CZE' = 'CZ',
                        'DEU' = 'DE',
                        'DNK' = 'DK',
                        'ESP' = 'ES',
                        'FIN' = 'FI',
                        'FRA' = 'FR',
                        'GBR' = 'GB',
                        'HUN' = 'HU',
                        'IRL' = 'IE',
                        'NLD' = 'NL',
                        'NOR' = 'NO',
                        'POL' = 'PL',
                        'PRT' = 'PT',
                        'SVN' = 'SI',
                        'SWE' = 'SE')) %>% 
  relocate(cntry, .after = LOCATION) %>% 
  pivot_wider(names_from = TIME, values_from = Value) %>% 
  select(cntry,
         "2002",
         "2003",
         "2010",
         "2011",
         "2012",
         "2018")

```


```{r load gini-data: Data from The World Bank}

# load gini data from second source
#gini_data2 <- read.csv("exam_data/API_SI.POV.GINI_DS2_en_csv_v2_2357065/API_SI.POV.GINI_DS2_en_csv_v2_2357065.csv", sep = ",")

# problematic csv-file so doing some manual loading of relevant rows without headers
gini_data2 = read.csv(
  "exam_data/API_SI.POV.GINI_DS2_en_csv_v2_2357065/API_SI.POV.GINI_DS2_en_csv_v2_2357065_edited3.csv",
  skip = 5,
  header = F)

# manually adding the headers
colnames(gini_data2) = (read.csv(
  "exam_data/API_SI.POV.GINI_DS2_en_csv_v2_2357065/API_SI.POV.GINI_DS2_en_csv_v2_2357065_edited3.csv",
  skip = 4,
  header = F,
  nrows = 1,
  as.is = T)
  )

func <- function(x, na.rm = F) x/100

# filter our relevant columns
gini_data2 <- gini_data2 %>% 
  mutate_if(is.numeric, func) %>% 
  filter(grepl('Belgium|Switzerland|Czech Republic|Germany|Denmark|Spain|Finland|France|United Kingdom|Hungary|Ireland|Netherlands|Norway|Poland|Portugal|Sweden|Slovenia',
               CountryName)) %>% 
  mutate(cntry = recode(CountryCode,
                        'BEL' = 'BE',
                        'CHE' = 'CH',
                        'CHZ' = 'CZ',
                        'DEU' = 'DE',
                        'DNK' = 'DK',
                        'ESP' = 'ES',
                        'FIN' = 'FI',
                        'FRA' = 'FR',
                        'GBR' = 'GB',
                        'HUN' = 'HU',
                        'IRL' = 'IE',
                        'NLD' = 'NL',
                        'NOR' = 'NO',
                        'POL' = 'PL',
                        'PRT' = 'PT',
                        'SVN' = 'SI',
                        'SWE' = 'SE')) %>% 
  select(cntry,
         "2002",
         "2003",
         "2010",
         "2011",
         "2012",
         "2018",
         #"2019", # Only N/As
         #"2020" # Only N/As
         )

gini_data2 <- gini_data2 %>% 
  mutate(WB_2002 = gini_data2$'2002',
         WB_2003 = gini_data2$'2003',
         WB_2010 = gini_data2$'2010',
         WB_2011 = gini_data2$'2011',
         WB_2012 = gini_data2$'2012',
         WB_2018 = gini_data2$'2018'
         ) %>% 
  select(cntry,
         WB_2002,
         WB_2003,
         WB_2010,
         WB_2011,
         WB_2012,
         WB_2018
         )

#cntrys_list2 <- c("Belgium",
#                 "Switzerland",
#                 "Czech Republic",
#                 "Germany",
#                 "Denmark",
#                 "Spain",
#                 "Finland",
#                 "France",
#                 "United Kingdom",
#                 "Hungary",
#                 "Ireland",
#                 "Netherlands",
#                 "Norway",
#                 "Poland",
#                 "Portugal",
#                 "Sweden",
#                 "Slovenia")

```


```{r merge gini data sets}

# merge OECD data and World Bank data
gini_data <- left_join(gini_data1, gini_data2, "cntry") %>% 
  mutate(
    y2002 = ifelse(is.na(gini_data$WB_2002),
                   ifelse(is.na(gini_data$'2002'), 
                          ifelse(is.na(gini_data$WB_2003), gini_data$'2003', gini_data$WB_2003),
                          gini_data$'2002'),
                   gini_data$WB_2002),
    
    y2010 = ifelse(is.na(gini_data$WB_2010),
                   ifelse(is.na(gini_data$'2010'),
                          ifelse(is.na(gini_data$WB_2011),
                                 ifelse(is.na(gini_data$'2011'),
                                        ifelse(is.na(gini_data$WB_2012), gini_data$'2012',
                                               gini_data$WB_2012),
                                        gini_data$'2011'),
                                 gini_data$WB_2011),
                          gini_data$'2010'),
                   gini_data$WB_2010),

    y2018 = ifelse(is.na(gini_data$WB_2018), gini_data$'2018', gini_data$WB_2018)
    ) %>% 
  select(cntry,
         y2002,
         y2010,
         y2018)
    
# plot gini data
gini_data %>% 
  ggplot() +
  aes(x = cntry, fill = cntry) +
  geom_density()

```


```{r eyeball plots of data, eval=FALSE, include=TRUE}

data02 %>%
  #subset(cntry == "SI" | cntry == "DK") %>% 
  ggplot() +
  aes(x = lrscale, color = cntry, fill = cntry) +
  geom_bar() +
  coord_cartesian(xlim = c(0, 10)) + 
  facet_wrap(vars(cntry))


data10 %>%
  #subset(cntry == "SI" | cntry == "DK") %>% 
  ggplot() +
  aes(x = lrscale, color = cntry, fill = cntry) +
  geom_bar() +
  coord_cartesian(xlim = c(0, 10)) + 
  facet_wrap(vars(cntry))

data18 %>%
  #subset(cntry == "SI" | cntry == "DK") %>% 
  ggplot() +
  aes(x = lrscale, color = cntry, fill = cntry) +
  geom_bar() +
  coord_cartesian(xlim = c(0, 10)) + 
  facet_wrap(vars(cntry))

```


```{r identify countries}

cntrys_02 <- c(levels(data02$cntry))
cntrys_10 <- c(levels(data10$cntry))
cntrys_18 <- c(levels(data18$cntry))

# trying to create a function to make this more smoothly...
# cntrys_list <- filter(cntrys_02 %in% cntrys_10)
# cntrys_list[sapply(cntrys_02, function(x) any(words %in% x))]

# create list fo countries in the 2002 data
#cntrys_18 <- c(levels(data18$cntry))

# filter out countries from 2010 not in 2018 data
data10 <- data10 %>% 
  filter(
    cntry %in% cntrys_02
  ) %>% 
  filter(
    cntry %in% cntrys_18
  )

# create list with updated countries in the updated 2010 data
#cntrys_10 <- c(levels(data10$cntry))

# filter out countries from 2018 not in 2010 data
data18 <- data18 %>% 
  filter(
    cntry %in% cntrys_10
  ) %>% 
  filter(
    cntry %in% cntrys_02
  )

# create list with updated countries in 2018 data
#cntrys_18 <- c(levels(data18$cntry))

# filter out countries from 2002 not in the updated 2018 data
data02 <- data02 %>% 
  filter(
    cntry %in% cntrys_10
  ) %>% 
  filter(
    cntry %in% cntrys_18
  )

```


```{r merge data}

cntrys_list <- c("BE",
                 "CH",
                 "CZ",
                 "DE",
                 "DK",
                 "ES",
                 "FI",
                 "FR",
                 "GB",
                 "HU",
                 "IE",
                 "NL",
                 "NO",
                 "PL",
                 "PT",
                 "SE",
                 "SI")

# merged data with all variables (some are N/As in the different surveys)
data_merged <- rbind.fill(data02, data10, data18) %>% 
  within(rm(inwdd,
            inwmm,
            inwyr,
            inwdds,
            inwmms,
            inwyys,
            edulvla,
            edulvlb)) %>% 
  mutate(
    essround = as_factor(essround),
    edition = as_factor(edition),
  ) %>% 
  subset(cntry %in% cntrys_list)

levels(data_merged$cntry)

# simple dataset with only the essential variables and no N/As
data_merged_simpl <- data_merged %>% 
  select(
    essround,
    edition,
    idno,
    date,
    month,
    year,
    cntry,
    lrscale,
    edulvl,
    eisced
    )


```
```{r plot merged data}

data_merged_simpl %>%
  group_by(essround) %>% 
  ggplot() +
  aes(x = cntry, fill = essround) +
  geom_bar()

```



```{r remove N/As}

# either have to remove all N/As or at least change their coding (e.g. "9999") to N/As


```





