---
title: "Untitled"
author: "Veronika Juhasz"
date: "5/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse, dplyr)

#setwd("/Users/veronikajuhasz/Documents/University/Cognitive_science_AU/Semester_4/Soc_cult/exam/Netlogo outputs")

#getwd()

```



to-dos:
- read in dataframes - DONE
- remove unneccessary rows (top section) - DONE
- leave only 1 ticks column, remove the rest - DONE
- rename column headers - DONE
- remove ticks over 2920 - DONE
- remove duplicates (keep every 10th row) - DONE
- make aggregate data per condition (sum the 10 trials per condition)
- compare conditions

```{r}

# problematic csv-file so doing some manual loading of relevant rows without headers

dataframe_try <- read.csv("netlogo_output/Condition_1/1exam_v13_groupbyopinion_movebycolor - cleared - fixed - FINAL Super combined plot.csv", skip = 46, header = T)


data.preprocessing <- function(dat) {
  dat %>% 
  select(
     ticks = x,
     mean_opinion_global = y,
     var_opinion_global = y.1,
     sd_opinion_global = y.2,
     mean_opinion_group_1 = y.3,
     var_opinion_group_1 = y.4,
     sd_opinion_group_1 = y.5,
     mean_opinion_group_0 = y.6,
     var_opinion_group_0 = y.7,
     sd_opinion_group_0 = y.8,
     mean_opinion_group_neg1 = y.9,
     var_opinion_group_neg1 = y.10,
     sd_opinion_group_neg1= y.11, 
     mean_opinion_left = y.12,
     var_opinion_left= y.13,
     sd_opinion_left= y.14,
     mean_opinion_mid_left= y.15,
     var_opinion_mid_left = y.16,
     sd_opinion_mid_left = y.17,
     mean_opinion_middle = y.18,
     var_opinion_middle = y.19,
     sd_opinion_middle = y.20,
     mean_opinion_mid_right= y.21,
     var_opinion_mid_right= y.22,
     sd_opinion_mid_right= y.23,
     mean_opinion_right = y.24,
     var_opinion_right = y.25,
     sd_opinion_right = y.26,
     polarization_index = y.27,
     percent_extremists= y.28,
     percent_extremists_1= y.29,
     percent_extremists_neg1= y.30 ) %>% 
  filter(
      ticks < 2921,
      row_number() %% 10 == 1)
}


dataframe_funtion_trial <- data.preprocessing(dataframe_try)


tbl <-
    list.files(path = "./Condition_1/",
               pattern = "*.csv", 
               full.names = T) %>% 
    map_df(~read_csv(., col_types = cols(.default = "c"), skip = 46, header = T)) 

```



